name: textlint
on: push
jobs:
  textlint:
    name: textlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 10.*
      - run: npm install
      - name: textlint
        run: npm test
